server:
  port: 3000

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
  datasource:
    url: jdbc:h2:~/dev/h2/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.company: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

