server:
  port: 3000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource

security:
  oauth2:
    client:
      client-id: id
      client-secret: secret

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    io.company: DEBUG

